name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# github 'push' 이벤트가 발생할 때 실행
on: [push]
jobs:
  github-actions-demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      # github의 체크아웃 액션 실행
      # 액션에 입력 파라메터 넘길 때 `with` 키 사용 (여기서는 'action-demo' 폴더에 코드 체크아웃 진행하겠다는 뜻)
      - uses: actions/checkout@v3
        with: 
          path: action-demo
      - run: ls -al
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node -v
